name: Speaker for the Dice
favicon: null
layout_spectrum: 0.5519474868196994
typography_spectrum: 0.6698493463918567
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.24220128147862852
  lightness: 0.6789689774159342
  saturation: 0.6136736585758626
  rhythmicContrast: 0.6481805744115263
purpose: []
